### ISSUE TITLE
About APPID

### ISSUE THREAD

**Issue by ghost** [BubiDevs/MyHomeAssistant#2]
Hello,

I'm the technical staff of CoolKit eWeLink, how did you get our APPID and APP Secret?

**Comment by andreabusi** [comment]
Hi Carl,
eWeLink integration doesn't use APPID or App Secret, it uses a custom integration called `HASS-sonoff-ewelink`.

**Comment by ghost** [comment]
> Hi Carl,
> eWeLink integration doesn't use APPID or App Secret, it uses a custom integration called `HASS-sonoff-ewelink`.

OK, I see. Thank you very much for your reply.
